/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerLoginRouteImport } from './routes/partner-login'
import { Route as PartnerDashboardRouteImport } from './routes/partner-dashboard'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OffersIndexRouteImport } from './routes/offers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentResultRouteImport } from './routes/payment.result'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as OrderSummaryOrderIdRouteImport } from './routes/order-summary.$orderId'
import { Route as OffersOfferIdRouteImport } from './routes/offers.$offerId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as BookingsConfirmationRouteImport } from './routes/bookings.confirmation'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AdminWebhookLogsRouteImport } from './routes/admin.webhook-logs'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrackingRouteImport } from './routes/admin.tracking'
import { Route as AdminSponsoredAdsRouteImport } from './routes/admin.sponsored-ads'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminPaymentRouteImport } from './routes/admin.payment'
import { Route as AdminPartnerPackagesRouteImport } from './routes/admin.partner-packages'
import { Route as AdminPartnerRouteImport } from './routes/admin.partner'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminHomeSlidersRouteImport } from './routes/admin.home-sliders'
import { Route as AdminFeaturedOffersRouteImport } from './routes/admin.featured-offers'
import { Route as AdminFavoritesRouteImport } from './routes/admin.favorites'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminCommissionRequestsRouteImport } from './routes/admin.commission-requests'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgreementsRouteImport } from './routes/admin.agreements'
import { Route as AdminAbandonedCartsRouteImport } from './routes/admin.abandoned-carts'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountMessagesRouteImport } from './routes/account.messages'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'
import { Route as AccountBookingsRouteImport } from './routes/account.bookings'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin.tickets.index'
import { Route as AccountTicketsIndexRouteImport } from './routes/account.tickets.index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as PartnerAgreementIdRouteImport } from './routes/partner.agreement.$id'
import { Route as OffersCategorySlugRouteImport } from './routes/offers.category.$slug'
import { Route as BookingPayBookingIdRouteImport } from './routes/booking.pay.$bookingId'
import { Route as AgreementViewIdRouteImport } from './routes/agreement.view.$id'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin.tickets.$ticketId'
import { Route as AdminSettingsTeamRouteImport } from './routes/admin.settings.team'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin.settings.profile'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin.settings.notifications'
import { Route as AdminSettingsIntegrationsRouteImport } from './routes/admin.settings.integrations'
import { Route as AdminSettingsAppearanceRouteImport } from './routes/admin.settings.appearance'
import { Route as AccountTicketsNewRouteImport } from './routes/account.tickets.new'
import { Route as AccountTicketsTicketIdRouteImport } from './routes/account.tickets.$ticketId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner-login',
  path: '/partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner-dashboard',
  path: '/partner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSummaryOrderIdRoute = OrderSummaryOrderIdRouteImport.update({
  id: '/order-summary/$orderId',
  path: '/order-summary/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersOfferIdRoute = OffersOfferIdRouteImport.update({
  id: '/offers/$offerId',
  path: '/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const BookingsConfirmationRoute = BookingsConfirmationRouteImport.update({
  id: '/bookings/confirmation',
  path: '/bookings/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhookLogsRoute = AdminWebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsoredAdsRoute = AdminSponsoredAdsRouteImport.update({
  id: '/sponsored-ads',
  path: '/sponsored-ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentRoute = AdminPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnerPackagesRoute = AdminPartnerPackagesRouteImport.update({
  id: '/partner-packages',
  path: '/partner-packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnerRoute = AdminPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeSlidersRoute = AdminHomeSlidersRouteImport.update({
  id: '/home-sliders',
  path: '/home-sliders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedOffersRoute = AdminFeaturedOffersRouteImport.update({
  id: '/featured-offers',
  path: '/featured-offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFavoritesRoute = AdminFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionRequestsRoute = AdminCommissionRequestsRouteImport.update({
  id: '/commission-requests',
  path: '/commission-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgreementsRoute = AdminAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedCartsRoute = AdminAbandonedCartsRouteImport.update({
  id: '/abandoned-carts',
  path: '/abandoned-carts',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMessagesRoute = AccountMessagesRouteImport.update({
  id: '/account/messages',
  path: '/account/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/account/favorites',
  path: '/account/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountTicketsIndexRoute = AccountTicketsIndexRouteImport.update({
  id: '/account/tickets/',
  path: '/account/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAgreementIdRoute = PartnerAgreementIdRouteImport.update({
  id: '/agreement/$id',
  path: '/agreement/$id',
  getParentRoute: () => PartnerRoute,
} as any)
const OffersCategorySlugRoute = OffersCategorySlugRouteImport.update({
  id: '/offers/category/$slug',
  path: '/offers/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPayBookingIdRoute = BookingPayBookingIdRouteImport.update({
  id: '/booking/pay/$bookingId',
  path: '/booking/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementViewIdRoute = AgreementViewIdRouteImport.update({
  id: '/agreement/view/$id',
  path: '/agreement/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsTeamRoute = AdminSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsIntegrationsRoute =
  AdminSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AccountTicketsNewRoute = AccountTicketsNewRouteImport.update({
  id: '/account/tickets/new',
  path: '/account/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTicketsTicketIdRoute = AccountTicketsTicketIdRouteImport.update({
  id: '/account/tickets/$ticketId',
  path: '/account/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/account/orders/$orderId',
  path: '/account/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/partner-login': typeof PartnerLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/agreements': typeof AdminAgreementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commission-requests': typeof AdminCommissionRequestsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/favorites': typeof AdminFavoritesRoute
  '/admin/featured-offers': typeof AdminFeaturedOffersRoute
  '/admin/home-sliders': typeof AdminHomeSlidersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/admin/partner-packages': typeof AdminPartnerPackagesRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/site': typeof AdminSiteRoute
  '/admin/sponsored-ads': typeof AdminSponsoredAdsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/auth/reset': typeof AuthResetRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/order-summary/$orderId': typeof OrderSummaryOrderIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/tickets/$ticketId': typeof AccountTicketsTicketIdRoute
  '/account/tickets/new': typeof AccountTicketsNewRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/agreement/view/$id': typeof AgreementViewIdRoute
  '/booking/pay/$bookingId': typeof BookingPayBookingIdRoute
  '/offers/category/$slug': typeof OffersCategorySlugRoute
  '/partner/agreement/$id': typeof PartnerAgreementIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/tickets/': typeof AccountTicketsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/partner-login': typeof PartnerLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/agreements': typeof AdminAgreementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commission-requests': typeof AdminCommissionRequestsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/favorites': typeof AdminFavoritesRoute
  '/admin/featured-offers': typeof AdminFeaturedOffersRoute
  '/admin/home-sliders': typeof AdminHomeSlidersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/admin/partner-packages': typeof AdminPartnerPackagesRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/site': typeof AdminSiteRoute
  '/admin/sponsored-ads': typeof AdminSponsoredAdsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/auth/reset': typeof AuthResetRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/order-summary/$orderId': typeof OrderSummaryOrderIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$id': typeof ProductIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/offers': typeof OffersIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/tickets/$ticketId': typeof AccountTicketsTicketIdRoute
  '/account/tickets/new': typeof AccountTicketsNewRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/agreement/view/$id': typeof AgreementViewIdRoute
  '/booking/pay/$bookingId': typeof BookingPayBookingIdRoute
  '/offers/category/$slug': typeof OffersCategorySlugRoute
  '/partner/agreement/$id': typeof PartnerAgreementIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/tickets': typeof AccountTicketsIndexRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRouteWithChildren
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/partner-login': typeof PartnerLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/messages': typeof AccountMessagesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/agreements': typeof AdminAgreementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commission-requests': typeof AdminCommissionRequestsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/favorites': typeof AdminFavoritesRoute
  '/admin/featured-offers': typeof AdminFeaturedOffersRoute
  '/admin/home-sliders': typeof AdminHomeSlidersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/partner': typeof AdminPartnerRoute
  '/admin/partner-packages': typeof AdminPartnerPackagesRoute
  '/admin/payment': typeof AdminPaymentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/site': typeof AdminSiteRoute
  '/admin/sponsored-ads': typeof AdminSponsoredAdsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/admin/webhook-logs': typeof AdminWebhookLogsRoute
  '/auth/reset': typeof AuthResetRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/order-summary/$orderId': typeof OrderSummaryOrderIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$id': typeof ProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/tickets/$ticketId': typeof AccountTicketsTicketIdRoute
  '/account/tickets/new': typeof AccountTicketsNewRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/agreement/view/$id': typeof AgreementViewIdRoute
  '/booking/pay/$bookingId': typeof BookingPayBookingIdRoute
  '/offers/category/$slug': typeof OffersCategorySlugRoute
  '/partner/agreement/$id': typeof PartnerAgreementIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/tickets/': typeof AccountTicketsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/partner-dashboard'
    | '/partner-login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/track'
    | '/verify'
    | '/verify-otp'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/messages'
    | '/account/profile'
    | '/admin/abandoned-carts'
    | '/admin/agreements'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/commission-requests'
    | '/admin/contact-messages'
    | '/admin/favorites'
    | '/admin/featured-offers'
    | '/admin/home-sliders'
    | '/admin/invoices'
    | '/admin/legal'
    | '/admin/merchants'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/partner'
    | '/admin/partner-packages'
    | '/admin/payment'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/sponsored-ads'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/verify'
    | '/admin/webhook-logs'
    | '/auth/reset'
    | '/booking/$bookingId'
    | '/bookings/confirmation'
    | '/checkout/failed'
    | '/checkout/success'
    | '/offers/$offerId'
    | '/order-summary/$orderId'
    | '/payment/failed'
    | '/payment/result'
    | '/product/$id'
    | '/account/'
    | '/admin/'
    | '/offers/'
    | '/account/orders/$orderId'
    | '/account/tickets/$ticketId'
    | '/account/tickets/new'
    | '/admin/settings/appearance'
    | '/admin/settings/integrations'
    | '/admin/settings/notifications'
    | '/admin/settings/profile'
    | '/admin/settings/team'
    | '/admin/tickets/$ticketId'
    | '/agreement/view/$id'
    | '/booking/pay/$bookingId'
    | '/offers/category/$slug'
    | '/partner/agreement/$id'
    | '/account/orders/'
    | '/account/tickets/'
    | '/admin/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/partner-dashboard'
    | '/partner-login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/track'
    | '/verify'
    | '/verify-otp'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/messages'
    | '/account/profile'
    | '/admin/abandoned-carts'
    | '/admin/agreements'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/commission-requests'
    | '/admin/contact-messages'
    | '/admin/favorites'
    | '/admin/featured-offers'
    | '/admin/home-sliders'
    | '/admin/invoices'
    | '/admin/legal'
    | '/admin/merchants'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/partner'
    | '/admin/partner-packages'
    | '/admin/payment'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/sponsored-ads'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/verify'
    | '/admin/webhook-logs'
    | '/auth/reset'
    | '/booking/$bookingId'
    | '/bookings/confirmation'
    | '/checkout/failed'
    | '/checkout/success'
    | '/offers/$offerId'
    | '/order-summary/$orderId'
    | '/payment/failed'
    | '/payment/result'
    | '/product/$id'
    | '/account'
    | '/admin'
    | '/offers'
    | '/account/orders/$orderId'
    | '/account/tickets/$ticketId'
    | '/account/tickets/new'
    | '/admin/settings/appearance'
    | '/admin/settings/integrations'
    | '/admin/settings/notifications'
    | '/admin/settings/profile'
    | '/admin/settings/team'
    | '/admin/tickets/$ticketId'
    | '/agreement/view/$id'
    | '/booking/pay/$bookingId'
    | '/offers/category/$slug'
    | '/partner/agreement/$id'
    | '/account/orders'
    | '/account/tickets'
    | '/admin/tickets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/partner-dashboard'
    | '/partner-login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/track'
    | '/verify'
    | '/verify-otp'
    | '/account/bookings'
    | '/account/favorites'
    | '/account/messages'
    | '/account/profile'
    | '/admin/abandoned-carts'
    | '/admin/agreements'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/commission-requests'
    | '/admin/contact-messages'
    | '/admin/favorites'
    | '/admin/featured-offers'
    | '/admin/home-sliders'
    | '/admin/invoices'
    | '/admin/legal'
    | '/admin/merchants'
    | '/admin/messages'
    | '/admin/offers'
    | '/admin/partner'
    | '/admin/partner-packages'
    | '/admin/payment'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schedule'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/sponsored-ads'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/verify'
    | '/admin/webhook-logs'
    | '/auth/reset'
    | '/booking/$bookingId'
    | '/bookings/confirmation'
    | '/checkout/failed'
    | '/checkout/success'
    | '/offers/$offerId'
    | '/order-summary/$orderId'
    | '/payment/failed'
    | '/payment/result'
    | '/product/$id'
    | '/account/'
    | '/admin/'
    | '/offers/'
    | '/account/orders/$orderId'
    | '/account/tickets/$ticketId'
    | '/account/tickets/new'
    | '/admin/settings/appearance'
    | '/admin/settings/integrations'
    | '/admin/settings/notifications'
    | '/admin/settings/profile'
    | '/admin/settings/team'
    | '/admin/tickets/$ticketId'
    | '/agreement/view/$id'
    | '/booking/pay/$bookingId'
    | '/offers/category/$slug'
    | '/partner/agreement/$id'
    | '/account/orders/'
    | '/account/tickets/'
    | '/admin/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  VerifyRoute: typeof VerifyRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountMessagesRoute: typeof AccountMessagesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AuthResetRoute: typeof AuthResetRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  BookingsConfirmationRoute: typeof BookingsConfirmationRoute
  OffersOfferIdRoute: typeof OffersOfferIdRoute
  OrderSummaryOrderIdRoute: typeof OrderSummaryOrderIdRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentResultRoute: typeof PaymentResultRoute
  ProductIdRoute: typeof ProductIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountTicketsTicketIdRoute: typeof AccountTicketsTicketIdRoute
  AccountTicketsNewRoute: typeof AccountTicketsNewRoute
  AgreementViewIdRoute: typeof AgreementViewIdRoute
  BookingPayBookingIdRoute: typeof BookingPayBookingIdRoute
  OffersCategorySlugRoute: typeof OffersCategorySlugRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AccountTicketsIndexRoute: typeof AccountTicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-login': {
      id: '/partner-login'
      path: '/partner-login'
      fullPath: '/partner-login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-dashboard': {
      id: '/partner-dashboard'
      path: '/partner-dashboard'
      fullPath: '/partner-dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-summary/$orderId': {
      id: '/order-summary/$orderId'
      path: '/order-summary/$orderId'
      fullPath: '/order-summary/$orderId'
      preLoaderRoute: typeof OrderSummaryOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$offerId': {
      id: '/offers/$offerId'
      path: '/offers/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof OffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/bookings/confirmation': {
      id: '/bookings/confirmation'
      path: '/bookings/confirmation'
      fullPath: '/bookings/confirmation'
      preLoaderRoute: typeof BookingsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhook-logs': {
      id: '/admin/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/admin/webhook-logs'
      preLoaderRoute: typeof AdminWebhookLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsored-ads': {
      id: '/admin/sponsored-ads'
      path: '/sponsored-ads'
      fullPath: '/admin/sponsored-ads'
      preLoaderRoute: typeof AdminSponsoredAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment': {
      id: '/admin/payment'
      path: '/payment'
      fullPath: '/admin/payment'
      preLoaderRoute: typeof AdminPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partner-packages': {
      id: '/admin/partner-packages'
      path: '/partner-packages'
      fullPath: '/admin/partner-packages'
      preLoaderRoute: typeof AdminPartnerPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partner': {
      id: '/admin/partner'
      path: '/partner'
      fullPath: '/admin/partner'
      preLoaderRoute: typeof AdminPartnerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-sliders': {
      id: '/admin/home-sliders'
      path: '/home-sliders'
      fullPath: '/admin/home-sliders'
      preLoaderRoute: typeof AdminHomeSlidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured-offers': {
      id: '/admin/featured-offers'
      path: '/featured-offers'
      fullPath: '/admin/featured-offers'
      preLoaderRoute: typeof AdminFeaturedOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/favorites': {
      id: '/admin/favorites'
      path: '/favorites'
      fullPath: '/admin/favorites'
      preLoaderRoute: typeof AdminFavoritesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commission-requests': {
      id: '/admin/commission-requests'
      path: '/commission-requests'
      fullPath: '/admin/commission-requests'
      preLoaderRoute: typeof AdminCommissionRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agreements': {
      id: '/admin/agreements'
      path: '/agreements'
      fullPath: '/admin/agreements'
      preLoaderRoute: typeof AdminAgreementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned-carts': {
      id: '/admin/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AdminAbandonedCartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/messages': {
      id: '/account/messages'
      path: '/account/messages'
      fullPath: '/account/messages'
      preLoaderRoute: typeof AccountMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/tickets/': {
      id: '/account/tickets/'
      path: '/account/tickets'
      fullPath: '/account/tickets/'
      preLoaderRoute: typeof AccountTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/agreement/$id': {
      id: '/partner/agreement/$id'
      path: '/agreement/$id'
      fullPath: '/partner/agreement/$id'
      preLoaderRoute: typeof PartnerAgreementIdRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/offers/category/$slug': {
      id: '/offers/category/$slug'
      path: '/offers/category/$slug'
      fullPath: '/offers/category/$slug'
      preLoaderRoute: typeof OffersCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/pay/$bookingId': {
      id: '/booking/pay/$bookingId'
      path: '/booking/pay/$bookingId'
      fullPath: '/booking/pay/$bookingId'
      preLoaderRoute: typeof BookingPayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/view/$id': {
      id: '/agreement/view/$id'
      path: '/agreement/view/$id'
      fullPath: '/agreement/view/$id'
      preLoaderRoute: typeof AgreementViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/team': {
      id: '/admin/settings/team'
      path: '/team'
      fullPath: '/admin/settings/team'
      preLoaderRoute: typeof AdminSettingsTeamRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/integrations': {
      id: '/admin/settings/integrations'
      path: '/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/account/tickets/new': {
      id: '/account/tickets/new'
      path: '/account/tickets/new'
      fullPath: '/account/tickets/new'
      preLoaderRoute: typeof AccountTicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/tickets/$ticketId': {
      id: '/account/tickets/$ticketId'
      path: '/account/tickets/$ticketId'
      fullPath: '/account/tickets/$ticketId'
      preLoaderRoute: typeof AccountTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/account/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsIntegrationsRoute: typeof AdminSettingsIntegrationsRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
  AdminSettingsTeamRoute: typeof AdminSettingsTeamRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsIntegrationsRoute: AdminSettingsIntegrationsRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
  AdminSettingsTeamRoute: AdminSettingsTeamRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAbandonedCartsRoute: typeof AdminAbandonedCartsRoute
  AdminAgreementsRoute: typeof AdminAgreementsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommissionRequestsRoute: typeof AdminCommissionRequestsRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminFavoritesRoute: typeof AdminFavoritesRoute
  AdminFeaturedOffersRoute: typeof AdminFeaturedOffersRoute
  AdminHomeSlidersRoute: typeof AdminHomeSlidersRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPartnerRoute: typeof AdminPartnerRoute
  AdminPartnerPackagesRoute: typeof AdminPartnerPackagesRoute
  AdminPaymentRoute: typeof AdminPaymentRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSponsoredAdsRoute: typeof AdminSponsoredAdsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminWebhookLogsRoute: typeof AdminWebhookLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedCartsRoute: AdminAbandonedCartsRoute,
  AdminAgreementsRoute: AdminAgreementsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCommissionRequestsRoute: AdminCommissionRequestsRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminFavoritesRoute: AdminFavoritesRoute,
  AdminFeaturedOffersRoute: AdminFeaturedOffersRoute,
  AdminHomeSlidersRoute: AdminHomeSlidersRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPartnerRoute: AdminPartnerRoute,
  AdminPartnerPackagesRoute: AdminPartnerPackagesRoute,
  AdminPaymentRoute: AdminPaymentRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminSiteRoute: AdminSiteRoute,
  AdminSponsoredAdsRoute: AdminSponsoredAdsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminWebhookLogsRoute: AdminWebhookLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface PartnerRouteChildren {
  PartnerAgreementIdRoute: typeof PartnerAgreementIdRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerAgreementIdRoute: PartnerAgreementIdRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  VerifyRoute: VerifyRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AccountBookingsRoute: AccountBookingsRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountMessagesRoute: AccountMessagesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AuthResetRoute: AuthResetRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  BookingsConfirmationRoute: BookingsConfirmationRoute,
  OffersOfferIdRoute: OffersOfferIdRoute,
  OrderSummaryOrderIdRoute: OrderSummaryOrderIdRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentResultRoute: PaymentResultRoute,
  ProductIdRoute: ProductIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountTicketsTicketIdRoute: AccountTicketsTicketIdRoute,
  AccountTicketsNewRoute: AccountTicketsNewRoute,
  AgreementViewIdRoute: AgreementViewIdRoute,
  BookingPayBookingIdRoute: BookingPayBookingIdRoute,
  OffersCategorySlugRoute: OffersCategorySlugRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AccountTicketsIndexRoute: AccountTicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
